# Site
name: 'San Francisco Daily Times'
description: "Keeping You Informed, Every Step of the Way"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/mundana-theme-jekyll'
disqus: 'demowebsite'
email: 'sfdt@gmail.com'
mailchimp-list: 'https:/sfdt.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    bao:
      name:           Bao Chi 
      avatar:         /assets/images/avatar1.jpg
      bio:            "Co-chief editor of the San Francisco Daily Times. The shorter one."
      email:          bao@sfdt.com


    william:
      name:           William 
      avatar:         /assets/images/avatar2.jpg
      bio:            "Co-chief editor of the San Francisco Daily Times. The taller one."
      email:          william@sfdt.com

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: bao
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]